#:schema ./alacritty-schema.json

[font]
normal = { family = "Cascadia Mono" }
bold = { family = "Cascadia Mono", style = "regular" }
bold_italic = { family = "Cascadia Mono", style = "regular" }
italic = { family = "Cascadia Mono", style = "regular" }

[window]
dimensions = { columns = 110, lines = 35 }
padding = { x = 12, y = 12 }
position = { x = 900, y = 500 }
dynamic_title = false
decorations = "full"

[shell]
program = "nu"

[mouse]
hide_when_typing = true

[colors.primary]
background = "#202020"
foreground = "#bdbdbd"

[colors.normal]
white = "#bdbdbd"
blue = "#4c90a8"
cyan = "#79af98"
green = "#879c54"
red = "#d95f5f"
yellow = "#cc8b00"
magenta = "#aa739a"

[colors.bright]
white = "#bdbdbd"
blue = "#4c90a8"
cyan = "#79af98"
green = "#879c54"
red = "#d95f5f"
yellow = "#cc8b00"
magenta = "#aa739a"

[colors.dim]
white = "#bdbdbd"
blue = "#4c90a8"
cyan = "#79af98"
green = "#879c54"
red = "#d95f5f"
yellow = "#cc8b00"
magenta = "#aa739a"

[colors.cursor]
cursor = "#bdbdbd"

[colors.vi_mode_cursor]
cursor = "#666666"

[cursor]
vi_mode_style.shape = "Block"
style.shape = "Underline"
