[font]
normal = { family = "Cascadia Mono" }
bold = { family = "Cascadia Mono", style = "regular" }
bold_italic = { family = "Cascadia Mono", style = "regular" }
italic = { family = "Cascadia Mono", style = "regular" }

[window]
dimensions = { columns = 110, lines = 35 }
padding = { x = 12, y = 12 }
position = { x = 800, y = 500 }
dynamic_title = false
# decorations = "none"

[shell]
program = "nu"

[mouse]
hide_when_typing = true

[colors]
# primary.background = "#262626"
primary.background = "#202020"

[colors.normal]
# white = "#d8d8d8"
white = "#cccccc"
[colors.bright]
# white = "#f8f8f8"
white = "#cccccc"
[colors.dim]
# white = "#8e8e8e"
