#:schema ./alacritty-schema.json

import = [
    "~/.config/alacritty/common.toml",
    # platform specific config file:
    # "~/.config/alacritty/platforms/macos.toml",
    # "~/.config/alacritty/platforms/windows.toml",
]
