[font]
size = 15

[window]
dimensions = { columns = 121, lines = 39 }
position = { x = 650, y = 390 }
decorations = "buttonless"

# [terminal.shell]
# program = "/etc/profiles/per-user/yusong/bin/nu"
# args = ["-l"]
